server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.206.130:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.206.130
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer‐ip‐address: true
IP: 12.34.56.12
